# è¦†å†™é…ç½®
# ä½œè€…ï¼šhttps://github.com/lamchey
# é¡¹ç›®åœ°å€ï¼šhttps://github.com/lamchey/HelloWorld
# æ—¶é—´ï¼š2024-10-17-14-21
proxy-providers:
  
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: âœˆ æ‰‹åŠ¨åˆ‡æ¢
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    type: select
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    interval: 300
    tolerance: 50  
  - name: ğŸš€ GitHub
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ“² Telegram
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ“¹ YouTube
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ‹ Docker
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ“º Bahamut
    type: select
    proxies: 
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ’¬ ChatGPT
    type: select
    proxies: 
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ¯ å…¨çƒç›´è¿
  - name: â“‚ï¸ Copilot
    type: select
    proxies: 
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ” è°·æ­ŒæœåŠ¡
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies: 
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â“‚ï¸ OneDrive
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies: 
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©      
  - name: ğŸ˜ï¸ å°ç±³æœåŠ¡
    type: select
    proxies: 
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies: 
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹      
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies: 
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: â›” å¹¿å‘Šå±è”½
    type: select
    proxies:
      - REJECT
  - name: ğŸš€ å…¨çƒä»£ç†
    type: select
    proxies: 
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT 
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
      - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
      - ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
      - âœˆ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|ğŸ‡­ğŸ‡°
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ğŸ‡¸ğŸ‡¬
    type: url-test
    interval: 300
    tolerance: 5
  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)å°|å°æ¹¾|æ–°åŒ—|å½°åŒ–|TW|Taiwan|ğŸ‡¹ğŸ‡¼
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)æ—¥æœ¬|å·æ—¥|ä¸œäº¬|JP|Japan|ğŸ‡¯ğŸ‡µ
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)ç¾|ç¾å›½|US|United States|ğŸ‡ºğŸ‡¸
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)è‹±å›½|UK|ğŸ‡¬ğŸ‡§
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)é©¬æ¥è¥¿äºš|Malaysia|ğŸ‡²ğŸ‡¾
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)åœŸè€³å…¶|Turkey|TÃ¼rkiye|ğŸ‡¹ğŸ‡·
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·èŠ‚ç‚¹
    include-all: true    
    exclude-filter: (?i)GB|Traffic|Expire|Premium|é¢‘é“|è®¢é˜…|ISP|æµé‡|åˆ°æœŸ|é‡ç½®
    filter: (?i)é˜¿æ ¹å»·|Argentina|ğŸ‡¦ğŸ‡·
    type: url-test
    interval: 300
    tolerance: 50
rule-providers:
  Custom_rules_Direct:
    url: https://ghp.ci/https://raw.githubusercontent.com/lamchey/HelloWorld/refs/heads/main/Rules/Direct.list
    path: ./ruleset/Custom_rules_Direct.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Lan:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
    path: ./ruleset/Lan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Direct:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list
    path: ./ruleset/Direct.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaDomain:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
    path: ./ruleset/ChinaDomain.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaIp:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs.list
    path: ./ruleset/ChinaIp.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleCN:
    url: https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  PT_Download:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
    path: ./ruleset/PT_Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BT_Download:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
    path: ./ruleset/BT_Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Telegram:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
    path: ./ruleset/Telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChatGPT:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
    path: ./ruleset/ChatGPT.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Copilot:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
    path: ./ruleset/Copilot.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GitHub:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
    path: ./ruleset/GitHub.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Apple:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
    path: ./ruleset/Apple.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Microsoft:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
    path: ./ruleset/Microsoft.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OneDrive:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
    path: ./ruleset/OneDrive.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  YouTube:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
    path: ./ruleset/YouTube.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Google:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
    path: ./ruleset/Google.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleFCM:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
    path: ./ruleset/GoogleFCM.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Docker:
    url: https://ghp.ci/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Docker/Docker.list
    path: ./ruleset/Docker.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  XiaoMi:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi.list
    path: ./ruleset/XiaoMi.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bahamut:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
    path: ./ruleset/Bahamut.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMedia:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
    path: ./ruleset/ChinaMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GlobalMedia:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
    path: ./ruleset/GlobalMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFW:
    url: https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list
    path: ./ruleset/ProxyGFW.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  antiAD:
    url: https://ghp.ci/https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
    path: ./ruleset/anti-AD.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  antiADwhite:
    url: https://ghp.ci/https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-for-clash.yaml
    path: ./ruleset/anti-AD-white.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
rules:
  # å»å¹¿å‘Šè§„åˆ™
  - "RULE-SET,antiADwhite,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,antiAD,â›” å¹¿å‘Šå±è”½"

  # è‡ªå®šä¹‰ç›´è¿è§„åˆ™
  - "RULE-SET,Custom_rules_Direct,ğŸ¯ å…¨çƒç›´è¿"

  # ç›´è¿è§„åˆ™
  - "RULE-SET,Lan,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,Direct,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,PT_Download,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,BT_Download,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿"
  
    # è‡ªå®šä¹‰ä»£ç†è§„åˆ™
  - "DOMAIN-SUFFIX,oyunfor.com,ğŸ‡¹ğŸ‡· åœŸè€³å…¶èŠ‚ç‚¹"

    # ä»£ç†è§„åˆ™
  - "RULE-SET,Docker,ğŸ‹ Docker"
  - "RULE-SET,GitHub,ğŸš€ GitHub"
  - "RULE-SET,Telegram,ğŸ“² Telegram"
  - "RULE-SET,ChatGPT,ğŸ’¬ ChatGPT"
  - "RULE-SET,Copilot,â“‚ï¸ Copilot"
  - "RULE-SET,YouTube,ğŸ“¹ YouTube"
  - "RULE-SET,Bahamut,ğŸ“º Bahamut"
  - "RULE-SET,ChinaMedia,ğŸŒ å›½å†…åª’ä½“"
  - "RULE-SET,GlobalMedia,ğŸŒ å›½å¤–åª’ä½“"
  - "RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM"
  - "RULE-SET,Google,ğŸ” è°·æ­ŒæœåŠ¡"
  - "RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡"
  - "RULE-SET,OneDrive,â“‚ï¸ OneDrive"
  - "RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡"
  - "RULE-SET,XiaoMi,ğŸ˜ï¸ å°ç±³æœåŠ¡"
  - "RULE-SET,ProxyGFW,ğŸš€ å…¨çƒä»£ç†"

    # ç›´è¿è§„åˆ™  
  - "RULE-SET,ChinaIp,ğŸ¯ å…¨çƒç›´è¿"
  
    # å…œåº•åˆ†æµ  
  - "MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼"
