rulesets:
  enabled: true
  overwrite_original_rules: true
  update_ruleset_on_request: true
  rulesets:
#  - {rule: "GEOIP,CN", group: "DIRECT"}
#  - {ruleset: "rules/LocalAreaNetwork.list", group: "DIRECT"}
#  - {ruleset: "surge:rules/LocalAreaNetwork.list", group: "DIRECT"}
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/lamchey/HelloWorld/refs/heads/main/Rules/Direct.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    
#      - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
#      - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
#      - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
#      - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
#      - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
#      - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
#      - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    
    
    
    
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    



#  - {ruleset: "clash-domain:https://ruleset.dev/clash_domestic_services_domains", group: "Domestic Services", interval: 86400}
#  - {ruleset: "clash-ipcidr:https://ruleset.dev/clash_domestic_services_ips", group: "Domestic Services", interval: 86400}
#  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml", group: "DIRECT", interval: 86400}

proxy_groups:
  custom_proxy_group:
#  - {name: UrlTest, type: url-test, rule: [".*"], url: http://www.gstatic.com/generate_204, interval: 300, tolerance: 100, timeout: 5}
#  - {name: Proxy, type: select, rule: [".*"]}
#  - {name: group1, type: select, rule: ["!!GROUPID=0"]}
#  - {name: v2ray, type: select, rule: ["!!GROUP=V2RayProvider"]}
#  - {import: snippets/groups_forcerule.txt}
#  - {name: ssid group, type: ssid, rule: ["default_group", "celluar=group0,ssid1=group1,ssid2=group2"]}
    - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, rule: DIRECT}
