custom:
  enable_rule_generator: true
  overwrite_original_rules: true
  proxy_groups:
    - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, rule: DIRECT}

    rulesets:
    - {ruleset: "Custom_rules_Direct:https://ghp.ci/https://raw.githubusercontent.com/lamchey/HelloWorld/refs/heads/main/Rules/Direct.list", group: "ğŸ¯ å…¨çƒç›´è¿", interval: 86400}
    
